import os

DEBUG = (os.getenv('DEBUG', 'False') == 'True')

# Messenger Database Settings
MESSENGER_DATABASE_ENABLED = (os.getenv('MESSAGE_DATABASE_ENABLED', 'True') == 'True')
MESSENGER_DATABASE_URL = os.getenv('MESSENGER_DATABASE_URL', 'mongodb://admin:kafka@localhost:27017/')
MESSENGER_DATABASE_NAME = os.getenv('MESSENGER_DATABASE_NAME', 'MESSAGES')
MESSENGER_DATABASE_TABLE = os.getenv('MESSAGE_DATABASE_TABLE', 'MESSAGES_RECIEVED')

# KAFKA Settings
KAFKA_ENABLED = (os.getenv('KAFKA_ENABLED', 'True') == 'True')

# Message and Experiment Settings
MESSAGE_SIZE_BYTES = int(os.getenv('MESSAGE_SIZE_BYTES', '100'))
EXPERIMENT_DURATION_HOURS = float(os.getenv('EXPERIMENT_DURATION_HOURS', '0'))
EXPERIMENT_MESSAGE_COUNT = int(os.getenv('EXPERIMENT_MESSAGE_COUNT', '0'))

TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
REQUEST_COUNT_LIMIT = int(os.getenv('REQUEST_COUNT_LIMIT', '3'))
REQUEST_ERROR_WAIT_TIME = int(os.getenv('REQUEST_ERROR_WAIT_TIME', '1'))

# Database Scheduler Settings
DATABASE_SCHEDULER_DATABASE = os.getenv('DATABASE_SCHEDULER_DATABASE', 'messages')
DATABASE_SCHEDULER_RECIPIENT_TABLE = os.getenv('DATABASE_SCHEDULER_RECIPIENT_TABLE', 'messages_recieved')

DATABASE_SCHEDULER_CASSANDRA_ENABLED = (os.getenv('DATABASE_SCHEDULER_CASSANDRA_ENABLED', 'True') == 'True')
DATABASE_SCHEDULER_CASSANDRA_HOST = os.getenv('DATABASE_SCHEDULER_CASSANDRA_HOST', 'localhost')

DATABASE_SCHEDULER_MYSQL_ENABLED = (os.getenv('DATABASE_SCHEDULER_MYSQL_ENABLED', 'True') == 'True')
DATABASE_SCHEDULER_MYSQL_HOST = os.getenv('DATABASE_SCHEDULER_MYSQL_HOST', 'localhost')
DATABASE_SCHEDULER_MYSQL_USER = os.getenv('DATABASE_SCHEDULER_MYSQL_USER', 'root')
DATABASE_SCHEDULER_MYSQL_PASSWORD = os.getenv('DATABASE_SCHEDULER_MYSQL_PASSWORD', 'kafka')

# Log file names
DOCKER_MONITOR_LOG_FILE = 'docker.log'
KAFKA_SCHEDULER_JOB_LOG_FILE = 'kafka-scheduler-job.log'
KAFKA_SCHEDULER_CONFIG_FILE = 'kafka-scheduler-config.json'