import os

# Enable debugging for detailed logs
DEBUG = (os.getenv('DEBUG', 'False') == 'True')

# KAFKA Settings
KAFKA_SERVER = os.getenv('KAFKA_SERVER', 'localhost:9092')

# Scheduled Message Worker Settings
WORKER_STATUS_LIST = ['READY', 'WORKING', 'DONE', 'ERROR']
WORKER_SCHEDULER_FREQ = 15
WORKER_READY_POLL_FREQ = 1
WORKER_WORKING_POLL_FREQ = 3
WORKER_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
WORKER_LOCK_TIMEOUT = 5
WORKER_STALE_TIME = 30
WORKER_THREAD_COUNT = 1
WORKER_PROCESS_COUNT = 8
WORKER_CONSUMER_TIMEOUT_MS = 1000

# Scheduled JOB Settings
JOB_STATUS_LIST = ['READY', 'WORKING', 'DONE', 'ERROR']
JOB_POLL_FREQ = 15
JOB_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
JOB_QUEUE_MAX_SIZE = 50
JOB_LOCK_TIMEOUT = 5

# Scheduled Messages Topic Settings
SM_TOPIC = 'SCHEDULED_MESSAGES'
SM_TOPIC_PARTITIONS = 50
SM_CONSUMER_GROUP_NAME = '__SM_GROUP'
SM_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
SM_MH_THREAD_COUNT = 8
SM_MH_PROCESS_COUNT = 8
SM_HEADER_JOB_ID_KEY = '__sm_job_id'

# Scheduled Message Bucketting Configuration
SM_MINIUMUM_DELAY = 30
SM_MAXIUMUM_DELAY = 400
SM_BUCKETS_MULTIPLICATION_RATIO = 2
SM_PARTITIONS_PER_BUCKET = 50
SM_BUCKET_TOPIC_FORMAT = '__SM_BUCKET_$start$_$end$'

# Configuration Server Settings
SERVER_HOST = os.getenv('SERVER_HOST', '0.0.0.0')
SERVER_PORT = os.getenv('SERVER_PORT', '8000')